### ISSUE TITLE
Add Google calendar component 

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#13]
Can't believe I haven't done this yet. Would make a good addition to the morning briefing to know what I have on today or for the rest of the week.

**Comment by kugan49** [comment]
Hello,
I look at your configuration because it is extremely well done and I arrive on the trash / recycling. And here is the only part that is more complex than mine: I use a specific google calendar to know which day is which pickup thanks to the keyword #trash in my event.

here is my config : 

```
- cal_id: xxxxxxxxxxxx@group.calendar.google.com                                                                                                                                                     
  entities:                                                                                                                                                                                                        
  - device_id: jace                                                                                                                                                                                                
    ignore_availability: true                                                                                                                                                                                      
    name: Jace                                                                                                                                                                                                     
    track: true                                                                                                                                                                                                    
    search: ""                                                                                                                                                                                                     
  - device_id: absence                                                                                                                                                                                             
    ignore_availability: true                                                                                                                                                                                      
    name: Absence                                                                                                                                                                                                  
    track: true                                                                                                                                                                                                    
    search: "#absence"                                                                                                                                                                                             
  - device_id: trash                                                                                                                                                                                               
    ignore_availability: true                                                                                                                                                                                      
    name: Ramassage ordures                                                                                                                                                                                        
    track: true                                                                                                                                                                                                    
    search: "#trash"                                                                                                                                                                                               

- cal_id: '#contacts@group.v.calendar.google.com'                                                                                                                                                                  
  entities:                                                                                                                                                                                                        
  - device_id: birthdays                                                                                                                                                                                           
    ignore_availability: true                                                                                                                                                                                      
    name: Anniversaires                                                                                                                                                                                            
    track: true                                                                                                                                                                                                    
```

 More information in my [github](https://github.com/kugan49/HA_Config/blob/master/config/packages/calendars.yaml)

Hoping that it serves you and inspires you for other improvements (I use it for my birthdays, and to know if I'm going to work and my schedules: heating management)
