### ISSUE TITLE
Little help in devices counts

### ISSUE THREAD

**Issue by codedmind** [JamesMcCarthy79/Home-Assistant-Config#154]
Hello and congrants in the config!!!
I think i'm late to the party (already follow same links and see the next big thing, can't wait to see it here)

For now i'm try to use some of your systemtab, i make the sensor count templates and have them but i cannot make it like you have, i copy and paste all the view in a new view but i never have it like the screenshot, for some reason it keeps the icons on the side...

![image](https://user-images.githubusercontent.com/2910047/84070186-9f076400-a9c3-11ea-9c39-761966524ecb.png)

Thanks

**Comment by BartEngelen** [comment]
Hello,
Try this for the custom: bar-card
```
entities:
  - entity: sensor.example
positions:
  icon: 'off'
  indicator: 'off'
  minmax: inside
  title: inside
  value: inside
title: Custom CSS Layout
type: 'custom:bar-card'
```

See here for more info: https://github.com/custom-cards/bar-card

Regards,

Bart

**Comment by codedmind** [comment]
@BartEngelen thanks for the hint... is a little better but not like @JamesMcCarthy79 pic :/

![image](https://user-images.githubusercontent.com/2910047/84141113-8db56a80-aa4a-11ea-9ce4-40c74577bf91.png)

**Comment by BartEngelen** [comment]
Hello,
I use the following code:
```
type: 'custom:bar-card'
entity: sensor.automation_count
animation:
  state: 'on'
  speed: 5
height: 40px
max: 40
positions:
  icon: 'off'
  indicator: inside
  minmax: 'off'
  title: inside
  value: inside
severity:
  - color: green
    from: 0
    to: 28
   - color: orange
     from: 29
     to: 39
  - color: red
    from: 40
    to: 50
title: Automations
width: 100%
```
![image](https://user-images.githubusercontent.com/17978789/84196664-d5ff7780-aaa0-11ea-8ac4-ce7889e7c8f4.png)
