### ISSUE TITLE
navigation_path: /lovelace/2

### ISSUE THREAD

**Issue by hwikene** [JamesMcCarthy79/Home-Assistant-Config#61]
Hi! 
I have tried to make same card as the one you made for "home" with house_4 picture. 
If you see in the code below. i cant figure out why you use "navigation_path: /lovelace/2. 
My card look almost like yours but i cant turn "off" the lights i have added to "binary_sensor.lights"

```
      - type: vertical-stack
        cards:
          - type: custom:card-modder
            card:
              type: picture-elements
              image: /local/house_4.png
              elements:
                - type: state-icon
                  icon: mdi:lightbulb
                  entity: binary_sensor.lights
                  tap_action: toggle
                  navigation_path: /lovelace/2 <--- Can you tell me what this is? 
                  style: {color: white, left: 52%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.alarm
                  style: {color: white, left: 5%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.doors
                  style: {color: white, left: 14%, top: 88%}
```

**Comment by JamesMcCarthy79** [comment]
Hi,

This is actually a piece of legacy code from the very early days of Lovelace, it used to navigate to my second tab of Lovalace where all my light switches used to be. This is now a binary_sensor so it will only show a representation of the lights being on/off but can't actually act as a switch. If you want it to switch you would have to use the service call function along with the data to call your lights.

```
      - type: vertical-stack
        cards:
          - type: custom:card-modder
            card:
              type: picture-elements
              image: /local/house_4.png
              elements:
                - type: state-icon
                  icon: mdi:lightbulb
                  entity: binary_sensor.lights
                  tap_action: call-service
                  service: input_boolean.toggle
                  service_data: {"entity_id": "input_boolean.downstairs_lighting"}
                  style: {color: white, left: 52%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.alarm
                  style: {color: white, left: 5%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.doors
                  style: {color: white, left: 14%, top: 88%}
```

The input_boolean would need to call a script which turns all of the lights you want on and another turning them off.  

Hope this helps let me know if you need more help with calling the scripts.

**Comment by JamesMcCarthy79** [comment]
actually there is a better way to do it, use the homeassistant call service to switch the group of lights on/off

```
      - type: vertical-stack
        cards:
          - type: custom:card-modder
            card:
              type: picture-elements
              image: /local/house_4.png
              elements:
                - type: state-icon
                  icon: mdi:lightbulb
                  entity: binary_sensor.lights
                  tap_action: call-service
                  service: homeassistant.toggle
                  service_data: {"entity_id": "group.downstairs_lights"}
                  style: {color: white, left: 52%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.alarm
                  style: {color: white, left: 5%, top: 88%}
                - type: state-icon
                  entity: binary_sensor.doors
                  style: {color: white, left: 14%, top: 88%}
```
